//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_SimpleVR_Ingame p_SimpleVR_Ingame;
        
        private static SteamVR_Input_ActionSet_SimpleVR_Menu p_SimpleVR_Menu;
        
        public static SteamVR_Input_ActionSet_SimpleVR_Ingame SimpleVR_Ingame
        {
            get
            {
                return SteamVR_Actions.p_SimpleVR_Ingame.GetCopy<SteamVR_Input_ActionSet_SimpleVR_Ingame>();
            }
        }
        
        public static SteamVR_Input_ActionSet_SimpleVR_Menu SimpleVR_Menu
        {
            get
            {
                return SteamVR_Actions.p_SimpleVR_Menu.GetCopy<SteamVR_Input_ActionSet_SimpleVR_Menu>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_SimpleVR_Ingame = ((SteamVR_Input_ActionSet_SimpleVR_Ingame)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_SimpleVR_Ingame>("/actions/SimpleVR_Ingame")));
            SteamVR_Actions.p_SimpleVR_Menu = ((SteamVR_Input_ActionSet_SimpleVR_Menu)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_SimpleVR_Menu>("/actions/SimpleVR_Menu")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions.SimpleVR_Ingame,
                    SteamVR_Actions.SimpleVR_Menu};
        }
    }
}
